# Generated by Django 6.0.5 on 2026-05-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='free_sessions_remaining',
            field=models.IntegerField(default=2),
        ),
    ]
