# Generated by Django 6.0.5 on 2026-05-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, help_text='Select a date and time for your session', null=True),
        ),
    ]
